# Generated by Django 3.2 on 2021-04-16 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_draw', models.FileField(upload_to='COMPONENT_PDF_DRAW')),
                ('png_draw', models.FileField(upload_to='COMPONENT_PNG_DRAW')),
                ('c_type', models.CharField(choices=[('PART', 'PART'), ('ASSEMBLY', 'ASSEMBLY')], default='PART', max_length=20)),
                ('material', models.CharField(default='default', max_length=150)),
                ('thickness', models.CharField(default='0', max_length=10)),
                ('band_count', models.CharField(default='0', max_length=10)),
                ('dxf_draw', models.FileField(null=True, upload_to='COMPONENT_DXF_FILE')),
                ('part_file', models.FileField(null=True, upload_to='COMPONENT_PART_FILE')),
                ('remainder', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('create', models.DateTimeField(default=django.utils.timezone.now)),
                ('p_class', models.CharField(choices=[('DEVICE', 'DEVICE'), ('PROJECT', 'PROJECT'), ('ORDER', 'ORDER'), ('COMPONENT', 'COMPONENT')], max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('n_email', models.EmailField(max_length=254)),
                ('contact_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readiness', models.DateField()),
                ('table', models.FileField(default=None, upload_to='ORDER_TABLE')),
                ('position_qr_code_list', models.FileField(default=None, upload_to='POSITION_QR_CODE_LIST')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.info')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('priority', models.IntegerField(default=0)),
                ('code', models.CharField(max_length=13)),
                ('pk_prod_qr_code', models.FileField(default=None, upload_to='PK_PROD_QR_CODE')),
                ('smart_prod_qr_code', models.FileField(default=None, upload_to='SMART_PROD_QR_CODE')),
                ('pdf_draw_wt_qr_code', models.FileField(default=None, upload_to='PDF_DRAW_WT_QR_CODE')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_primary_manual_roats', to='MainApp.component')),
                ('m_assembly', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_secondary_manual_roats', to='MainApp.component')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.order')),
            ],
        ),
        migrations.CreateModel(
            name='StoragePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('n_row', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('act', models.BooleanField()),
                ('create', models.DateTimeField(default=django.utils.timezone.now)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.position')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.device')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.info')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_status', models.CharField(choices=[('DESIGNER', 'DESIGNER'), ('PRODUCTION', 'PRODUCTION'), ('GUEST', 'GUEST')], default='GUEST', max_length=100)),
                ('phone', models.CharField(default='+38(099) 099-99-99', max_length=20)),
                ('new_email', models.CharField(default='new_net@gmail.com', max_length=100)),
                ('profile_user_name', models.CharField(default='Name', max_length=20)),
                ('profile_user_last', models.CharField(default='Surname', max_length=20)),
                ('active_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.order')),
                ('active_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.project')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.storageplace'),
        ),
        migrations.AddField(
            model_name='order',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.project'),
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('priority', models.IntegerField(default=0)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.manufacturer')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.info'),
        ),
        migrations.AddField(
            model_name='component',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.info'),
        ),
        migrations.CreateModel(
            name='AnAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NONE', 'NONE'), ('CREATE', 'CREATE'), ('WORK', 'WORK'), ('DONE', 'DONE')], max_length=20)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.operation')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.position')),
            ],
        ),
    ]
