# Generated by Django 3.2 on 2021-04-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='dxf_draw',
            field=models.FileField(blank=True, null=True, upload_to='COMPONENT_DXF_FILE'),
        ),
        migrations.AlterField(
            model_name='component',
            name='part_file',
            field=models.FileField(blank=True, null=True, upload_to='COMPONENT_PART_FILE'),
        ),
        migrations.AlterField(
            model_name='component',
            name='pdf_draw',
            field=models.FileField(blank=True, null=True, upload_to='COMPONENT_PDF_DRAW'),
        ),
        migrations.AlterField(
            model_name='component',
            name='png_draw',
            field=models.FileField(blank=True, null=True, upload_to='COMPONENT_PNG_DRAW'),
        ),
    ]
