# Generated by Django 3.2 on 2021-04-19 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_alter_info_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MainApp.info'),
        ),
    ]
