# Generated by Django 3.2 on 2021-04-19 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_alter_device_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MainApp.info'),
        ),
        migrations.AlterField(
            model_name='order',
            name='info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MainApp.info'),
        ),
        migrations.AlterField(
            model_name='project',
            name='info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MainApp.info'),
        ),
    ]
