# Generated by Django 3.2 on 2021-04-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_auto_20210419_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='readiness',
            field=models.DateTimeField(),
        ),
    ]
