# Generated by Django 3.2 on 2021-04-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_alter_order_readiness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='readiness',
            field=models.DateField(),
        ),
    ]
